### ISSUE TITLE
Click on Setting is raising error _. not defined

### ISSUE THREAD

**Issue by fernando-CWP** [googlesamples/gmail-add-ons-samples#11]
Hi, I'm new with Addons

When click on Settings and on Schedule a Meeting I get the same error. I need help because I don't know why. Is any library required?

ReferenceError:  _ not defined.
Stack trace
	at Settings:115 (cachedPropertiesForUser_)
	at Settings:34 (getSettingsForUser)
	at ActionHandlers:177
	at Main:103 (dispatchActionInternal)
	at Main:65 (handleShowSettings)

Code at line 115 in Settings.js:
return _.assign(Object.create(cachedPropertiesPrototype), {
    properties: PropertiesService.getUserProperties(),
    cache: CacheService.getUserCache()
  });

**Comment by sqrrrl** [comment]
_ is from lodash. Did you copy dist/3p-bundle.gs into your script project?

**Comment by fernando-CWP** [comment]
No, I didn't. Problem solved. Thanks
